### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sonyakun** [sonyakun/misspy#3]
# Unimplemented Misskey endpoints
We omit those that do not explain the use of the API.
- [x] antennas/
- [x] federation/
- [x] i/
- [x] mute/
- [x] #4
## notes
- [x] notes/favorites/
- [x] notes/featured
- [x] notes/*-timeline
- [x] notes/timeline
- [x] notes/mentions
- [x] notes/polls
- [x] notes/reactions
- [x] notes/replies
- [x] notes/search-by-tag
- [x] notes/search
- [x] notes/show
- [x] notes/state
- [x] notes/thread-muting/
- [x] notes/unrenote
- [x] notes/translate
- [x] notes/user-list-timeline
- [x] notes/watching/
## 
- [x] clips/
- [x] drive/
- [x] users/
- [x] username/available
- [x] email-address/available
- [x] following/
- [x] hashtags/
~~- [ ] i/webhooks/~~
- [x] pages/

**Comment by sonyakun** [comment]
I was able to implement the whole thing in something like 4 hours🤔
All that remains is a PullRequest.

**Comment by sonyakun** [comment]
Merge in #5
